import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter } from 'next/font/google'
 
const inter = Inter({
  subsets : ["latin"],
  weight : ["100","200","300","400","500","600","700","800","900"]
});
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className,"light","antialiased")}>{children}</body>
    </html>
  )
}

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={cn(`${geistSans.variable,"light"} ${geistMono.variable} antialiased`)}>
//         {children}
//       </body>
//     </html>
//   );
// }
 